
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="description" content="Pakistan: Administrative Division (Provinces and Districts) featured by population statistics in maps and charts.">
<title>Pakistan: Administrative Division (Provinces and Districts) - Population Statistics in Maps and Charts</title>
<link rel="shortcut icon" href="/favicon.ico">
<script>var pagemode = 'adminpage'; var isAdmin = true; var pageid = 'pakistan-admin'; var pagelang = 'en'; var pagelabel = "Administrative Division"; var popDate = 'C 1998-03-01'; var years = 17; var start_x = 69; var start_y = 31; var start_level = 6; var swap_width = 1045; var hor_percent = 41; var vert_percent = 44; var swap = true; var mapcopyright = 'Map data by U.S. Bureau of Census: Demobase Pakistan (web).'; var objid = ''; var objtype = ''; var startmap = 'phys'; var lev_num = 2; var edit_mode = ''; var locale = 'tr'; var placeLocale = null; wikiFromWD = false;</script>
<script src="js/pakistan.js"></script>
<script src="/js/cp_data_m.js"></script>
<script src="/js/cp_loc.js"></script>
<script src="/js/cp_menu.js"></script>
<script src="/js/cp_charts_m.js"></script>
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script src="/jquery/jquery-3.1.1.min.js"></script>
<script src="/js/cp_phpbase_m.js"></script>
<script>cp.init(pagelang,vizMode)</script>
<script src="/js/cp_phpadmin_m.js"></script>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<style>
article#admtable { top: 44%; }
div#admmap { height: 44%; }
@media all and (min-width: 1045px) {
	article#admtable { top: 26px; left: calc(180px + 41%); }
	div#admmap { height: auto; bottom: -1px; width: 41% }
	header.admpage { left: calc(180px + 41%) }
	div#headline { left: calc(162px + 41%) }
}
</style>
</head>
<body onload="init_data(); start_maps()" itemscope="" itemtype="http://schema.org/Country">
<script>writeMenu('en')</script>
<div class="mobiadv">
	<script>show_mobiadv();</script>
</div>
<div id="headline" class="hor">
	<div id="orient">
		<a href="/">Home</a>&nbsp;&nbsp;&#8594;&nbsp;&nbsp;<span itemprop="containedIn" itemscope="" itemtype="http://schema.org/Continent"><a itemprop="url" href="/Asia.html"><span itemprop="name">Asia</span></a></span>&nbsp;&nbsp;&#8594;&nbsp;&nbsp;<span itemprop="containedIn" itemscope="" itemtype="http://schema.org/Country"><a itemprop="url" href="../Pakistan.html"><span itemprop="name">Pakistan</span></a></span>
	</div>
	<div id="social">
		<div class="changelang"><a href="javascript:cp.changePageLang('en','de')"><img src="/images/icons/de.svg" title="Deutsch" alt=""></a></div>
	</div>
</div>
<div id="inforowdiv" class="info" style="display:none"></div>
<article class="cpage swapped" id="admtable">
<header class="admpage">
<a href="javascript:openMap()"><img id="smap" title="Show Map" alt="Show Map" src="/images/smaps/Pakistan-100T.png"></a>
<h1><a href="../Pakistan.html"><span itemprop="name">Pakistan</span></a>: <span class="smalltext">Administrative Division</span></h1>
</header>
<script>handleArticleResize()</script>
<h2><span class="noviz">Contents: </span>Provinces and Districts</h2>
<p>The census population of the provinces, federal territories, districts and agencies of Pakistan in the boundaries of 2014.</p>
<table class="data" id="tl">
<thead>
<tr><th class="rname" data-coltype="name" onclick="javascript:sort('tl',0,false)"><a href="javascript:sort('tl',0,false)">Name</a></th><th class="rstatus" data-coltype="status" onclick="javascript:sort('tl',1,false)"><a href="javascript:sort('tl',1,false)">Status</a></th><th class="rpop prio3" data-coltype="pop" data-coldate="1972-09-16" data-colhead="C 1972-09-16" onclick="javascript:sort('tl',2,true)"><a href="javascript:sort('tl',2,true)">Population</a><br><span class="unit">Census<br>1972-09-16</span></th><th class="rpop prio2" data-coltype="pop" data-coldate="1981-03-01" data-colhead="C 1981-03-01" onclick="javascript:sort('tl',3,true)"><a href="javascript:sort('tl',3,true)">Population</a><br><span class="unit">Census<br>1981-03-01</span></th><th class="rpop prio1" data-coltype="pop" data-coldate="1998-03-01" data-colhead="C 1998-03-01" onclick="javascript:sort('tl',4,true)"><a href="javascript:sort('tl',4,true)">Population</a><br><span class="unit">Census<br>1998-03-01</span></th><th data-coltype="other" class="sc"></th></tr>
</thead>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('2')"><td class="rname" id="i2" data-wiki="Balochistan, Pakistan" data-wd="Q163239" data-area="345765.34" data-density="18.99"><a href="javascript:sym('2')"><span itemprop="name">Balochistan</span></a></td><td class="rstatus">Province</td><td class="rpop prio3">2,428,678</td><td class="rpop prio2">4,332,376</td><td class="rpop prio1">6,565,885</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=2">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('201')"><td class="rname" id="i201" data-wiki="Awaran District" data-wd="Q250800" data-area="24992.3" data-density="4.73"><a href="javascript:sym('201')"><span itemprop="name">Awaran</span></a></td><td class="rstatus">District</td><td class="rpop prio3">51,918</td><td class="rpop prio2">110,353</td><td class="rpop prio1">118,173</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=201">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('202')"><td class="rname" id="i202" data-wiki="Barkhan District" data-wd="Q250810" data-area="3588.76" data-density="28.85"><a href="javascript:sym('202')"><span itemprop="name">Barkhan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">44,704</td><td class="rpop prio2">61,686</td><td class="rpop prio1">103,545</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=202">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('204')"><td class="rname" id="i204" data-wiki="Chagai District" data-wd="Q276717" data-area="44020.93" data-density="2.37"><a href="javascript:sym('204')"><span itemprop="name">Chagai</span></a></td><td class="rstatus">District</td><td class="rpop prio3">34,034</td><td class="rpop prio2">63,713</td><td class="rpop prio1">104,534</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=204">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('205')"><td class="rname" id="i205" data-wiki="Dera Bugti District" data-wd="Q2315565" data-area="10356.24" data-density="17.51"><a href="javascript:sym('205')"><span itemprop="name">Dera Bugti</span></a></td><td class="rstatus">District</td><td class="rpop prio3">52,718</td><td class="rpop prio2">103,821</td><td class="rpop prio1">181,310</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=205">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('206')"><td class="rname" id="i206" data-wiki="Gwadar District" data-wd="Q2081818" data-area="12456.42" data-density="14.89"><a href="javascript:sym('206')"><span itemprop="name">Gwadar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">90,820</td><td class="rpop prio2">112,385</td><td class="rpop prio1">185,498</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=206">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('228')"><td class="rname" id="i228" data-wiki="Harnai District" data-wd="Q2995304" data-area="3055.1" data-density="25.09"><a href="javascript:sym('228')"><span itemprop="name">Harnai</span></a></td><td class="rstatus">District</td><td class="rpop prio3">28,130</td><td class="rpop prio2">40,013</td><td class="rpop prio1">76,652</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=228">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('207')"><td class="rname" id="i207" data-wiki="Jafarabad District" data-wd="Q595921" data-area="2533.09" data-density="170.87"><a href="javascript:sym('207')"><span itemprop="name">Jaffarabad</span></a> (<span itemprop="name">incl. Sohbatpur</span>)</td><td class="rstatus">District</td><td class="rpop prio3">179,981</td><td class="rpop prio2">265,342</td><td class="rpop prio1">432,817</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=207">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('208')"><td class="rname" id="i208" data-wiki="Jhal Magsi District" data-wd="Q2633556" data-area="3861.33" data-density="28.47"><a href="javascript:sym('208')"><span itemprop="name">Jhal Magsi</span></a></td><td class="rstatus">District</td><td class="rpop prio3">75,261</td><td class="rpop prio2">68,092</td><td class="rpop prio1">109,941</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=208">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('203')"><td class="rname" id="i203" data-wiki="Kachhi District" data-wd="Q2281302" data-area="6674.45" data-density="38.28"><a href="javascript:sym('203')"><span itemprop="name">Kachhi</span></a> (<span itemprop="name">Bolan</span>)</td><td class="rstatus">District</td><td class="rpop prio3">123,720</td><td class="rpop prio2">200,863</td><td class="rpop prio1">255,480</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=203">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('209')"><td class="rname" id="i209" data-wiki="Kalat District" data-wd="Q611142" data-area="13624.49" data-density="17.46"><a href="javascript:sym('209')"><span itemprop="name">Kalat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">71,746</td><td class="rpop prio2">209,149</td><td class="rpop prio1">237,834</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=209">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('210')"><td class="rname" id="i210" data-wiki="Kech District" data-wd="Q276716" data-area="23764.15" data-density="17.39"><a href="javascript:sym('210')"><span itemprop="name">Kech</span></a></td><td class="rstatus">District</td><td class="rpop prio3">147,978</td><td class="rpop prio2">379,467</td><td class="rpop prio1">413,204</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=210">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('211')"><td class="rname" id="i211" data-wiki="Kharan District" data-wd="Q537334" data-area="15416.33" data-density="7.56"><a href="javascript:sym('211')"><span itemprop="name">Kharan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">45,770</td><td class="rpop prio2">69,226</td><td class="rpop prio1">116,541</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=211">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('212')"><td class="rname" id="i212" data-wiki="Khuzdar District" data-wd="Q2642523" data-area="30757.67" data-density="13.57"><a href="javascript:sym('212')"><span itemprop="name">Khuzdar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">146,207</td><td class="rpop prio2">276,449</td><td class="rpop prio1">417,466</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=212">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('213')"><td class="rname" id="i213" data-wiki="Killa Abdullah District" data-wd="Q100106" data-area="5675.75" data-density="63.56"><a href="javascript:sym('213')"><span itemprop="name">Killa Abdullah</span></a></td><td class="rstatus">District</td><td class="rpop prio3">113,215</td><td class="rpop prio2">170,590</td><td class="rpop prio1">360,724</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=213">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('226')"><td class="rname" id="i226" data-wiki="Killa Saifullah District" data-wd="Q153340" data-area="12331.38" data-density="15.7"><a href="javascript:sym('226')"><span itemprop="name">Killa Saifullah</span></a></td><td class="rstatus">District</td><td class="rpop prio3">72,086</td><td class="rpop prio2">148,362</td><td class="rpop prio1">193,553</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=226">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('214')"><td class="rname" id="i214" data-wiki="Kohlu District" data-wd="Q2315604" data-area="7707.24" data-density="12.95"><a href="javascript:sym('214')"><span itemprop="name">Kohlu</span></a></td><td class="rstatus">District</td><td class="rpop prio3">55,497</td><td class="rpop prio2">71,269</td><td class="rpop prio1">99,846</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=214">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('215')"><td class="rname" id="i215" data-wiki="Lasbela District" data-wd="Q44942" data-area="15006.27" data-density="20.84"><a href="javascript:sym('215')"><span itemprop="name">Lasbela</span></a></td><td class="rstatus">District</td><td class="rpop prio3">125,263</td><td class="rpop prio2">188,139</td><td class="rpop prio1">312,695</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=215">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('229')"><td class="rname" id="i229" data-wiki="Lehri District" data-wd="Q23043443" data-area="1951.68" data-density="16.69"><a href="javascript:sym('229')"><span itemprop="name">Lehri</span></a></td><td class="rstatus">District</td><td class="rpop prio3">22,312</td><td class="rpop prio2">36,260</td><td class="rpop prio1">32,576</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=229">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('216')"><td class="rname" id="i216" data-wiki="Loralai District" data-wd="Q2281268" data-area="8114.36" data-density="30.83"><a href="javascript:sym('216')"><span itemprop="name">Loralai</span></a></td><td class="rstatus">District</td><td class="rpop prio3">84,366</td><td class="rpop prio2">204,055</td><td class="rpop prio1">250,147</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=216">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('217')"><td class="rname" id="i217" data-wiki="Mastung District" data-wd="Q1026625" data-area="5540.43" data-density="28.98"><a href="javascript:sym('217')"><span itemprop="name">Mastung</span></a></td><td class="rstatus">District</td><td class="rpop prio3">74,690</td><td class="rpop prio2">130,207</td><td class="rpop prio1">160,546</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=217">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('227')"><td class="rname" id="i227" data-wiki="Musakhel District, Pakistan" data-wd="Q2315489" data-area="5729.9" data-density="23.4"><a href="javascript:sym('227')"><span itemprop="name">Musakhel</span></a></td><td class="rstatus">District</td><td class="rpop prio3">38,547</td><td class="rpop prio2">91,174</td><td class="rpop prio1">134,056</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=227">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('218')"><td class="rname" id="i218" data-wiki="Nasirabad District" data-wd="Q2315447" data-area="3216.36" data-density="76.45"><a href="javascript:sym('218')"><span itemprop="name">Nasirabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">43,893</td><td class="rpop prio2">129,112</td><td class="rpop prio1">245,894</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=218">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('225')"><td class="rname" id="i225" data-wiki="Nushki District" data-wd="Q2427113" data-area="5591.27" data-density="17.53"><a href="javascript:sym('225')"><span itemprop="name">Nushki</span></a></td><td class="rstatus">District</td><td class="rpop prio3">31,261</td><td class="rpop prio2">56,742</td><td class="rpop prio1">98,030</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=225">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('219')"><td class="rname" id="i219" data-wiki="Panjgur District" data-wd="Q2428944" data-area="17151.67" data-density="13.65"><a href="javascript:sym('219')"><span itemprop="name">Panjgur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">56,820</td><td class="rpop prio2">160,750</td><td class="rpop prio1">234,051</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=219">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('220')"><td class="rname" id="i220" data-wiki="Pishin District" data-wd="Q2281172" data-area="4912.15" data-density="76.69"><a href="javascript:sym('220')"><span itemprop="name">Pishin</span></a></td><td class="rstatus">District</td><td class="rpop prio3">135,939</td><td class="rpop prio2">208,007</td><td class="rpop prio1">376,728</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=220">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('221')"><td class="rname" id="i221" data-wiki="Quetta District" data-wd="Q2315549" data-area="2732.42" data-density="279.62"><a href="javascript:sym('221')"><span itemprop="name">Quetta</span></a></td><td class="rstatus">District</td><td class="rpop prio3">252,577</td><td class="rpop prio2">383,403</td><td class="rpop prio1">764,040</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=221">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('230')"><td class="rname" id="i230" data-wiki="Sherani District" data-wd="Q2414501" data-area="2731.93" data-density="29.9"><a href="javascript:sym('230')"><span itemprop="name">Sheerani</span></a> (<span itemprop="name">Sherani</span>)</td><td class="rstatus">District</td><td class="rpop prio3">25,384</td><td class="rpop prio2">78,625</td><td class="rpop prio1">81,684</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=230">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('222')"><td class="rname" id="i222" data-wiki="Sibi District" data-wd="Q2483088" data-area="4952.64" data-density="20.95"><a href="javascript:sym('222')"><span itemprop="name">Sibi</span></a></td><td class="rstatus">District</td><td class="rpop prio3">60,604</td><td class="rpop prio2">58,469</td><td class="rpop prio1">103,746</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=222">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('231')"><td class="rname" id="i231" data-wiki="Washuk District" data-wd="Q643102" data-area="32196.84" data-density="2.81"><a href="javascript:sym('231')"><span itemprop="name">Washuk</span></a></td><td class="rstatus">District</td><td class="rpop prio3">31,030</td><td class="rpop prio2">58,814</td><td class="rpop prio1">90,368</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=231">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('223')"><td class="rname" id="i223" data-wiki="Zhob District" data-wd="Q2281313" data-area="11858.57" data-density="16.31"><a href="javascript:sym('223')"><span itemprop="name">Zhob</span></a></td><td class="rstatus">District</td><td class="rpop prio3">74,519</td><td class="rpop prio2">134,660</td><td class="rpop prio1">193,458</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=223">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('224')"><td class="rname" id="i224" data-wiki="Ziarat District" data-wd="Q2315423" data-area="3263.21" data-density="24.74"><a href="javascript:sym('224')"><span itemprop="name">Ziarat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">37,688</td><td class="rpop prio2">63,179</td><td class="rpop prio1">80,748</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=224">&#8594;</a></td></tr>
</tbody>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('4')"><td class="rname" id="i4" data-wiki="Federally Administered Tribal Areas" data-wd="Q208270" data-area="27295.16" data-density="116.37"><a href="javascript:sym('4')"><span itemprop="name">Federally Administered Tribal Areas</span></a> (<span itemprop="name">FATA</span>)</td><td class="rstatus">Federal Territory</td><td class="rpop prio3">2,491,230</td><td class="rpop prio2">2,198,547</td><td class="rpop prio1">3,176,331</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=4">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('401')"><td class="rname" id="i401" data-wiki="Bajaur Agency" data-wd="Q804133" data-area="1533.15" data-density="388.24"><a href="javascript:sym('401')"><span itemprop="name">Bajaur</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">364,050</td><td class="rpop prio2">289,206</td><td class="rpop prio1">595,227</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=401">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('409')"><td class="rname" id="i409" data-wiki="Frontier Region Bannu" data-wd="Q2594879" data-area="681.89" data-density="28.73"><a href="javascript:sym('409')"><span itemprop="name">Frontier Region Bannu</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">50,778</td><td class="rpop prio2">63,213</td><td class="rpop prio1">19,593</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=409">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('410')"><td class="rname" id="i410" data-wiki="Frontier Region Dera Ismail Khan" data-wd="Q1074426" data-area="1904" data-density="20.48"><a href="javascript:sym('410')"><span itemprop="name">Frontier Region Dera Ismail Khan</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">49,822</td><td class="rpop prio2">55,824</td><td class="rpop prio1">38,990</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=410">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('411')"><td class="rname" id="i411" data-wiki="Frontier Region Kohat" data-wd="Q1071234" data-area="459.52" data-density="192.5"><a href="javascript:sym('411')"><span itemprop="name">Frontier Region Kohat</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">44,042</td><td class="rpop prio2">57,245</td><td class="rpop prio1">88,456</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=411">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('408')"><td class="rname" id="i408" data-wiki="Frontier Region Lakki Marwat" data-wd="Q2594888" data-area="285.39" data-density="24.48"><a href="javascript:sym('408')"><span itemprop="name">Frontier Region Lakki Marwat</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">13,104</td><td class="rpop prio2">16,149</td><td class="rpop prio1">6,987</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=408">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('412')"><td class="rname" id="i412" data-wiki="Frontier Region Peshawar" data-wd="Q1071206" data-area="256.45" data-density="209.95"><a href="javascript:sym('412')"><span itemprop="name">Frontier Region Peshawar</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">60,132</td><td class="rpop prio2">37,061</td><td class="rpop prio1">53,841</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=412">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('413')"><td class="rname" id="i413" data-wiki="Frontier Region Tank" data-wd="Q1068316" data-area="1403.81" data-density="19.39"><a href="javascript:sym('413')"><span itemprop="name">Frontier Region Tank</span></a></td><td class="rstatus">Adjoining Tribal Area</td><td class="rpop prio3">26,616</td><td class="rpop prio2">30,183</td><td class="rpop prio1">27,216</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=413">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('402')"><td class="rname" id="i402" data-wiki="Khyber Agency" data-wd="Q2373383" data-area="2884.5" data-density="189.54"><a href="javascript:sym('402')"><span itemprop="name">Khyber</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">378,032</td><td class="rpop prio2">284,256</td><td class="rpop prio1">546,730</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=402">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('403')"><td class="rname" id="i403" data-wiki="Kurram Valley" data-wd="Q2378590" data-area="3342.12" data-density="134.14"><a href="javascript:sym('403')"><span itemprop="name">Kurram</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">279,998</td><td class="rpop prio2">294,362</td><td class="rpop prio1">448,310</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=403">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('404')"><td class="rname" id="i404" data-wiki="Mohmand Agency" data-wd="Q1579737" data-area="2089.71" data-density="160.05"><a href="javascript:sym('404')"><span itemprop="name">Mohmand</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">382,922</td><td class="rpop prio2">163,933</td><td class="rpop prio1">334,453</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=404">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('405')"><td class="rname" id="i405" data-wiki="North Waziristan" data-wd="Q1915545" data-area="4928.55" data-density="73.3"><a href="javascript:sym('405')"><span itemprop="name">North Waziristan</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">250,663</td><td class="rpop prio2">238,910</td><td class="rpop prio1">361,246</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=405">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('406')"><td class="rname" id="i406" data-wiki="Orakzai Agency" data-wd="Q2580389" data-area="1284.42" data-density="175.52"><a href="javascript:sym('406')"><span itemprop="name">Orakzai</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">283,557</td><td class="rpop prio2">358,751</td><td class="rpop prio1">225,441</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=406">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('407')"><td class="rname" id="i407" data-wiki="South Waziristan" data-wd="Q1798701" data-area="6242.79" data-density="68.85"><a href="javascript:sym('407')"><span itemprop="name">South Waziristan</span></a></td><td class="rstatus">Tribal District (Agency)</td><td class="rpop prio3">307,514</td><td class="rpop prio2">309,454</td><td class="rpop prio1">429,841</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=407">&#8594;</a></td></tr>
</tbody>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('5')"><td class="rname" id="i5" data-wiki="Islamabad Capital Territory" data-wd="Q848613" data-area="897.83" data-density="896.87"><a href="javascript:sym('5')"><span itemprop="name">Islamabad</span></a></td><td class="rstatus">Capital Territory</td><td class="rpop prio3">237,549</td><td class="rpop prio2">340,286</td><td class="rpop prio1">805,235</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=5">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('501')"><td class="rname" id="i501" data-wiki="Islamabad" data-wd="Q1362" data-area="897.83" data-density="896.87"><a href="javascript:sym('501')"><span itemprop="name">Islamabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">237,549</td><td class="rpop prio2">340,286</td><td class="rpop prio1">805,235</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=501">&#8594;</a></td></tr>
</tbody>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('6')"><td class="rname" id="i6" data-wiki="Khyber Pakhtunkhwa" data-wd="Q183314" data-area="74852.3" data-density="237.05"><a href="javascript:sym('6')"><span itemprop="name">Khyber Pakhtunkhwa</span></a> (<span itemprop="name">North-West Frontier</span>)</td><td class="rstatus">Province</td><td class="rpop prio3">8,388,551</td><td class="rpop prio2">11,061,328</td><td class="rpop prio1">17,743,645</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=6">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('601')"><td class="rname" id="i601" data-wiki="Abbottabad District" data-wd="Q306799" data-area="1745.32" data-density="504.59"><a href="javascript:sym('601')"><span itemprop="name">Abbottabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">524,826</td><td class="rpop prio2">647,635</td><td class="rpop prio1">880,666</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=601">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('602')"><td class="rname" id="i602" data-wiki="Bannu District" data-wd="Q3030995" data-area="1172.38" data-density="576.32"><a href="javascript:sym('602')"><span itemprop="name">Bannu</span></a></td><td class="rstatus">District</td><td class="rpop prio3">341,690</td><td class="rpop prio2">422,027</td><td class="rpop prio1">675,667</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=602">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('603')"><td class="rname" id="i603" data-wiki="Battagram District" data-wd="Q3240074" data-area="1354.17" data-density="226.91"><a href="javascript:sym('603')"><span itemprop="name">Batagram</span></a></td><td class="rstatus">District</td><td class="rpop prio3">174,009</td><td class="rpop prio2">339,119</td><td class="rpop prio1">307,278</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=603">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('604')"><td class="rname" id="i604" data-wiki="Buner District" data-wd="Q2039096" data-area="1749.29" data-density="289.29"><a href="javascript:sym('604')"><span itemprop="name">Buner</span></a></td><td class="rstatus">District</td><td class="rpop prio3">187,984</td><td class="rpop prio2">265,517</td><td class="rpop prio1">506,048</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=604">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('605')"><td class="rname" id="i605" data-wiki="Charsadda District, Pakistan" data-wd="Q2379089" data-area="981.9" data-density="1041.21"><a href="javascript:sym('605')"><span itemprop="name">Charsadda</span></a></td><td class="rstatus">District</td><td class="rpop prio3">513,193</td><td class="rpop prio2">630,811</td><td class="rpop prio1">1,022,364</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=605">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('606')"><td class="rname" id="i606" data-wiki="Chitral District" data-wd="Q878510" data-area="15023.85" data-density="21.21"><a href="javascript:sym('606')"><span itemprop="name">Chitral</span></a></td><td class="rstatus">District</td><td class="rpop prio3">159,000</td><td class="rpop prio2">208,560</td><td class="rpop prio1">318,689</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=606">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('607')"><td class="rname" id="i607" data-wiki="Dera Ismail Khan District" data-wd="Q284210" data-area="7272.99" data-density="117.28"><a href="javascript:sym('607')"><span itemprop="name">Dera Ismail Khan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">380,229</td><td class="rpop prio2">494,432</td><td class="rpop prio1">852,995</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=607">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('608')"><td class="rname" id="i608" data-wiki="Hangu District, Pakistan" data-wd="Q2379105" data-area="1375.12" data-density="228.73"><a href="javascript:sym('608')"><span itemprop="name">Hangu</span></a></td><td class="rstatus">District</td><td class="rpop prio3">125,721</td><td class="rpop prio2">182,474</td><td class="rpop prio1">314,529</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=608">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('609')"><td class="rname" id="i609" data-wiki="Haripur District" data-wd="Q13410476" data-area="1929.11" data-density="358.83"><a href="javascript:sym('609')"><span itemprop="name">Haripur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">417,561</td><td class="rpop prio2">479,031</td><td class="rpop prio1">692,228</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=609">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('610')"><td class="rname" id="i610" data-wiki="Karak District" data-wd="Q1114427" data-area="2662.1" data-density="161.83"><a href="javascript:sym('610')"><span itemprop="name">Karak</span></a></td><td class="rstatus">District</td><td class="rpop prio3">191,204</td><td class="rpop prio2">249,681</td><td class="rpop prio1">430,796</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=610">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('611')"><td class="rname" id="i611" data-wiki="Kohat District" data-wd="Q1250340" data-area="2990.18" data-density="188.16"><a href="javascript:sym('611')"><span itemprop="name">Kohat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">264,465</td><td class="rpop prio2">326,617</td><td class="rpop prio1">562,644</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=611">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('613')"><td class="rname" id="i613" data-wiki="Lakki Marwat District" data-wd="Q2039074" data-area="3207.16" data-density="152.79"><a href="javascript:sym('613')"><span itemprop="name">Lakki Marwat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">225,529</td><td class="rpop prio2">288,759</td><td class="rpop prio1">490,025</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=613">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('614')"><td class="rname" id="i614" data-wiki="Lower Dir District" data-wd="Q2358299" data-area="1571.33" data-density="456.72"><a href="javascript:sym('614')"><span itemprop="name">Lower Dir</span></a></td><td class="rstatus">District</td><td class="rpop prio3">277,481</td><td class="rpop prio2">404,844</td><td class="rpop prio1">717,649</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=614">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('612')"><td class="rname" id="i612" data-wiki="Lower Kohistan District" data-wd="Q25653361" data-area="1845.61" data-density="155.95"><a href="javascript:sym('612')"><span itemprop="name">Lower Kohistan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">82,992</td><td class="rpop prio2">285,113</td><td class="rpop prio1">287,824</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=612">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('615')"><td class="rname" id="i615" data-wiki="Malakand District" data-wd="Q3240564" data-area="949.86" data-density="476.17"><a href="javascript:sym('615')"><span itemprop="name">Malakand Protected Area</span></a></td><td class="rstatus">District</td><td class="rpop prio3">185,872</td><td class="rpop prio2">257,797</td><td class="rpop prio1">452,291</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=615">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('616')"><td class="rname" id="i616" data-wiki="Mansehra District" data-wd="Q2358309" data-area="4262.34" data-density="226.23"><a href="javascript:sym('616')"><span itemprop="name">Mansehra</span></a></td><td class="rstatus">District</td><td class="rpop prio3">638,504</td><td class="rpop prio2">631,012</td><td class="rpop prio1">964,287</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=616">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('617')"><td class="rname" id="i617" data-wiki="Mardan District" data-wd="Q2379056" data-area="1654.77" data-density="882.36"><a href="javascript:sym('617')"><span itemprop="name">Mardan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">696,622</td><td class="rpop prio2">881,465</td><td class="rpop prio1">1,460,100</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=617">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('618')"><td class="rname" id="i618" data-wiki="Nowshera District" data-wd="Q1585944" data-area="1734.73" data-density="504.04"><a href="javascript:sym('618')"><span itemprop="name">Nowshera</span></a></td><td class="rstatus">District</td><td class="rpop prio3">410,718</td><td class="rpop prio2">537,638</td><td class="rpop prio1">874,373</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=618">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('619')"><td class="rname" id="i619" data-wiki="Peshawar District" data-wd="Q549467" data-area="1335.66" data-density="1517.49"><a href="javascript:sym('619')"><span itemprop="name">Peshawar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">807,012</td><td class="rpop prio2">1,113,303</td><td class="rpop prio1">2,026,851</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=619">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('620')"><td class="rname" id="i620" data-wiki="Shangla District" data-wd="Q2379122" data-area="1390.67" data-density="312.48"><a href="javascript:sym('620')"><span itemprop="name">Shangla</span></a></td><td class="rstatus">District</td><td class="rpop prio3">179,813</td><td class="rpop prio2">251,546</td><td class="rpop prio1">434,563</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=620">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('621')"><td class="rname" id="i621" data-wiki="Swabi District" data-wd="Q281247" data-area="1484.89" data-density="691.5"><a href="javascript:sym('621')"><span itemprop="name">Swabi</span></a></td><td class="rstatus">District</td><td class="rpop prio3">507,631</td><td class="rpop prio2">625,035</td><td class="rpop prio1">1,026,804</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=621">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('622')"><td class="rname" id="i622" data-wiki="Swat District" data-wd="Q389161" data-area="5431.1" data-density="231.56"><a href="javascript:sym('622')"><span itemprop="name">Swat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">520,614</td><td class="rpop prio2">715,938</td><td class="rpop prio1">1,257,602</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=622">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('623')"><td class="rname" id="i623" data-wiki="Tank District" data-wd="Q10955614" data-area="1664.36" data-density="143.13"><a href="javascript:sym('623')"><span itemprop="name">Tank</span></a></td><td class="rstatus">District</td><td class="rpop prio3">93,389</td><td class="rpop prio2">141,062</td><td class="rpop prio1">238,216</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=623">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('626')"><td class="rname" id="i626" data-wiki="Torghar District" data-wd="Q2981085" data-area="497.79" data-density="378.78"><a href="javascript:sym('626')"><span itemprop="name">Tor Ghar</span></a> (<span itemprop="name">Kala Dhaka</span>)</td><td class="rstatus">District</td><td class="rpop prio3">109,918</td><td class="rpop prio2">139,223</td><td class="rpop prio1">188,552</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=626">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('624')"><td class="rname" id="i624" data-wiki="Upper Dir District" data-wd="Q1517502" data-area="3752.83" data-density="153.45"><a href="javascript:sym('624')"><span itemprop="name">Upper Dir</span></a></td><td class="rstatus">District</td><td class="rpop prio3">251,045</td><td class="rpop prio2">362,565</td><td class="rpop prio1">575,858</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=624">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('625')"><td class="rname" id="i625" data-wiki="Upper Kohistan District" data-wd="Q20972958" data-area="5812.82" data-density="31.78"><a href="javascript:sym('625')"><span itemprop="name">Upper Kohistan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">121,529</td><td class="rpop prio2">180,124</td><td class="rpop prio1">184,746</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=625">&#8594;</a></td></tr>
</tbody>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('7')"><td class="rname" id="i7" data-wiki="Punjab, Pakistan" data-wd="Q4478" data-area="204668.35" data-density="359.71"><a href="javascript:sym('7')"><span itemprop="name">Punjab</span></a></td><td class="rstatus">Province</td><td class="rpop prio3">37,607,423</td><td class="rpop prio2">47,292,441</td><td class="rpop prio1">73,621,290</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=7">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('701')"><td class="rname" id="i701" data-wiki="Attock District" data-wd="Q2283119" data-area="6819.85" data-density="186.94"><a href="javascript:sym('701')"><span itemprop="name">Attock</span></a></td><td class="rstatus">District</td><td class="rpop prio3">748,890</td><td class="rpop prio2">876,667</td><td class="rpop prio1">1,274,935</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=701">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('702')"><td class="rname" id="i702" data-wiki="Bahawalnagar District" data-wd="Q2315465" data-area="8559.1" data-density="240.85"><a href="javascript:sym('702')"><span itemprop="name">Bahawalnagar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,073,891</td><td class="rpop prio2">1,373,747</td><td class="rpop prio1">2,061,447</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=702">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('703')"><td class="rname" id="i703" data-wiki="Bahawalpur District" data-wd="Q2281250" data-area="23922.35" data-density="101.71"><a href="javascript:sym('703')"><span itemprop="name">Bahawalpur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,071,026</td><td class="rpop prio2">1,453,438</td><td class="rpop prio1">2,433,091</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=703">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('704')"><td class="rname" id="i704" data-wiki="Bhakkar District" data-wd="Q2315520" data-area="8576.98" data-density="122.59"><a href="javascript:sym('704')"><span itemprop="name">Bhakkar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">500,498</td><td class="rpop prio2">665,884</td><td class="rpop prio1">1,051,456</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=704">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('705')"><td class="rname" id="i705" data-wiki="Chakwal District" data-wd="Q2315496" data-area="6616.23" data-density="163.8"><a href="javascript:sym('705')"><span itemprop="name">Chakwal</span></a></td><td class="rstatus">District</td><td class="rpop prio3">692,802</td><td class="rpop prio2">775,600</td><td class="rpop prio1">1,083,725</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=705">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('735')"><td class="rname" id="i735" data-wiki="Chiniot District" data-wd="Q2503822" data-area="2598.75" data-density="371.38"><a href="javascript:sym('735')"><span itemprop="name">Chiniot</span></a></td><td class="rstatus">District</td><td class="rpop prio3">570,775</td><td class="rpop prio2">694,080</td><td class="rpop prio1">965,124</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=735">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('706')"><td class="rname" id="i706" data-wiki="Dera Ghazi Khan District" data-wd="Q2315476" data-area="11764.64" data-density="139.67"><a href="javascript:sym('706')"><span itemprop="name">Dera Ghazi Khan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">686,057</td><td class="rpop prio2">943,663</td><td class="rpop prio1">1,643,118</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=706">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('707')"><td class="rname" id="i707" data-wiki="Faisalabad District" data-wd="Q2281194" data-area="5936.76" data-density="914.56"><a href="javascript:sym('707')"><span itemprop="name">Faisalabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">3,163,756</td><td class="rpop prio2">3,561,909</td><td class="rpop prio1">5,429,547</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=707">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('708')"><td class="rname" id="i708" data-wiki="Gujranwala District" data-wd="Q2281238" data-area="3617.29" data-density="940.19"><a href="javascript:sym('708')"><span itemprop="name">Gujranwala</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,615,568</td><td class="rpop prio2">2,108,365</td><td class="rpop prio1">3,400,940</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=708">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('709')"><td class="rname" id="i709" data-wiki="Gujrat District" data-wd="Q45303" data-area="3087.32" data-density="663.36"><a href="javascript:sym('709')"><span itemprop="name">Gujrat</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,177,345</td><td class="rpop prio2">1,408,585</td><td class="rpop prio1">2,048,008</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=709">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('710')"><td class="rname" id="i710" data-wiki="Hafizabad District" data-wd="Q2281213" data-area="2275.57" data-density="366.05"><a href="javascript:sym('710')"><span itemprop="name">Hafizabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">444,187</td><td class="rpop prio2">567,572</td><td class="rpop prio1">832,980</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=710">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('711')"><td class="rname" id="i711" data-wiki="Jhang District" data-wd="Q936703" data-area="6333.35" data-density="295.17"><a href="javascript:sym('711')"><span itemprop="name">Jhang</span></a></td><td class="rstatus">District</td><td class="rpop prio3">983,818</td><td class="rpop prio2">1,276,864</td><td class="rpop prio1">1,869,421</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=711">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('712')"><td class="rname" id="i712" data-wiki="Jhelum District" data-wd="Q32429" data-area="3610.34" data-density="259.52"><a href="javascript:sym('712')"><span itemprop="name">Jhelum</span></a></td><td class="rstatus">District</td><td class="rpop prio3">591,906</td><td class="rpop prio2">659,012</td><td class="rpop prio1">936,957</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=712">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('713')"><td class="rname" id="i713" data-wiki="Kasur District" data-wd="Q2503839" data-area="3922.17" data-density="605.76"><a href="javascript:sym('713')"><span itemprop="name">Kasur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,186,386</td><td class="rpop prio2">1,528,002</td><td class="rpop prio1">2,375,875</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=713">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('714')"><td class="rname" id="i714" data-wiki="Khanewal District" data-wd="Q48787" data-area="4344.97" data-density="476.07"><a href="javascript:sym('714')"><span itemprop="name">Khanewal</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,067,993</td><td class="rpop prio2">1,369,766</td><td class="rpop prio1">2,068,490</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=714">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('715')"><td class="rname" id="i715" data-wiki="Khushab District" data-wd="Q2625301" data-area="6596.12" data-density="137.31"><a href="javascript:sym('715')"><span itemprop="name">Khushab</span></a></td><td class="rstatus">District</td><td class="rpop prio3">543,314</td><td class="rpop prio2">641,366</td><td class="rpop prio1">905,711</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=715">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('716')"><td class="rname" id="i716" data-wiki="Lahore District" data-wd="Q2315527" data-area="1687.35" data-density="3744.77"><a href="javascript:sym('716')"><span itemprop="name">Lahore</span></a></td><td class="rstatus">District</td><td class="rpop prio3">2,587,621</td><td class="rpop prio2">3,544,942</td><td class="rpop prio1">6,318,745</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=716">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('717')"><td class="rname" id="i717" data-wiki="Layyah District" data-wd="Q2418995" data-area="6335.21" data-density="176.94"><a href="javascript:sym('717')"><span itemprop="name">Layyah</span></a></td><td class="rstatus">District</td><td class="rpop prio3">495,537</td><td class="rpop prio2">666,517</td><td class="rpop prio1">1,120,951</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=717">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('718')"><td class="rname" id="i718" data-wiki="Lodhran District" data-wd="Q2503767" data-area="2659.86" data-density="440.55"><a href="javascript:sym('718')"><span itemprop="name">Lodhran</span></a></td><td class="rstatus">District</td><td class="rpop prio3">558,793</td><td class="rpop prio2">739,912</td><td class="rpop prio1">1,171,800</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=718">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('719')"><td class="rname" id="i719" data-wiki="Mandi Bahauddin District" data-wd="Q2419031" data-area="2755.54" data-density="421.17"><a href="javascript:sym('719')"><span itemprop="name">Mandi Bahauddin</span></a></td><td class="rstatus">District</td><td class="rpop prio3">721,833</td><td class="rpop prio2">846,114</td><td class="rpop prio1">1,160,552</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=719">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('720')"><td class="rname" id="i720" data-wiki="Mianwali District" data-wd="Q2419042" data-area="5993.21" data-density="176.3"><a href="javascript:sym('720')"><span itemprop="name">Mianwali</span></a></td><td class="rstatus">District</td><td class="rpop prio3">595,134</td><td class="rpop prio2">711,529</td><td class="rpop prio1">1,056,620</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=720">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('721')"><td class="rname" id="i721" data-wiki="Multan District" data-wd="Q2281168" data-area="3638.5" data-density="856.63"><a href="javascript:sym('721')"><span itemprop="name">Multan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,506,223</td><td class="rpop prio2">1,970,075</td><td class="rpop prio1">3,116,851</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=721">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('722')"><td class="rname" id="i722" data-wiki="Muzaffargarh District" data-wd="Q12156132" data-area="7668.29" data-density="343.74"><a href="javascript:sym('722')"><span itemprop="name">Muzaffargarh</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,069,358</td><td class="rpop prio2">1,497,736</td><td class="rpop prio1">2,635,903</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=722">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('736')"><td class="rname" id="i736" data-wiki="Nankana Sahib District" data-wd="Q2503781" data-area="1624.44" data-density="421.04"><a href="javascript:sym('736')"><span itemprop="name">Nankana Sahib</span></a></td><td class="rstatus">District</td><td class="rpop prio3">419,091</td><td class="rpop prio2">509,313</td><td class="rpop prio1">683,963</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=736">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('723')"><td class="rname" id="i723" data-wiki="Narowal District" data-wd="Q2419016" data-area="2333.64" data-density="542.11"><a href="javascript:sym('723')"><span itemprop="name">Narowal</span></a></td><td class="rstatus">District</td><td class="rpop prio3">834,501</td><td class="rpop prio2">908,977</td><td class="rpop prio1">1,265,097</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=723">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('724')"><td class="rname" id="i724" data-wiki="Okara District" data-wd="Q46785" data-area="4421.74" data-density="505"><a href="javascript:sym('724')"><span itemprop="name">Okara</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,123,812</td><td class="rpop prio2">1,487,261</td><td class="rpop prio1">2,232,992</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=724">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('725')"><td class="rname" id="i725" data-wiki="Pakpattan District" data-wd="Q121203" data-area="2876.8" data-density="447.26"><a href="javascript:sym('725')"><span itemprop="name">Pakpattan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">615,742</td><td class="rpop prio2">843,623</td><td class="rpop prio1">1,286,680</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=725">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('726')"><td class="rname" id="i726" data-wiki="Rahim Yar Khan District" data-wd="Q2639823" data-area="12746.5" data-density="246.42"><a href="javascript:sym('726')"><span itemprop="name">Rahim Yar Khan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,398,879</td><td class="rpop prio2">1,841,451</td><td class="rpop prio1">3,141,053</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=726">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('727')"><td class="rname" id="i727" data-wiki="Rajanpur District" data-wd="Q2418966" data-area="12302.48" data-density="89.71"><a href="javascript:sym('727')"><span itemprop="name">Rajanpur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">456,391</td><td class="rpop prio2">638,921</td><td class="rpop prio1">1,103,618</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=727">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('728')"><td class="rname" id="i728" data-wiki="Rawalpindi District" data-wd="Q24440" data-area="5231.12" data-density="643.06"><a href="javascript:sym('728')"><span itemprop="name">Rawalpindi</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,744,949</td><td class="rpop prio2">2,121,450</td><td class="rpop prio1">3,363,911</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=728">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('729')"><td class="rname" id="i729" data-wiki="Sahiwal District" data-wd="Q2418927" data-area="3220.8" data-density="572.28"><a href="javascript:sym('729')"><span itemprop="name">Sahiwal</span></a></td><td class="rstatus">District</td><td class="rpop prio3">944,656</td><td class="rpop prio2">1,281,526</td><td class="rpop prio1">1,843,194</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=729">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('730')"><td class="rname" id="i730" data-wiki="Sargodha District" data-wd="Q2315589" data-area="5767.51" data-density="462.24"><a href="javascript:sym('730')"><span itemprop="name">Sargodha</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,557,641</td><td class="rpop prio2">1,911,849</td><td class="rpop prio1">2,665,979</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=730">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('731')"><td class="rname" id="i731" data-wiki="Sheikhupura District" data-wd="Q2503836" data-area="4182.82" data-density="630.45"><a href="javascript:sym('731')"><span itemprop="name">Sheikhupura</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,237,865</td><td class="rpop prio2">1,600,840</td><td class="rpop prio1">2,637,066</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=731">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('732')"><td class="rname" id="i732" data-wiki="Sialkot District" data-wd="Q2315579" data-area="3079.04" data-density="884.52"><a href="javascript:sym('732')"><span itemprop="name">Sialkot</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,509,424</td><td class="rpop prio2">1,802,505</td><td class="rpop prio1">2,723,481</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=732">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('733')"><td class="rname" id="i733" data-wiki="Toba Tek Singh District" data-wd="Q45206" data-area="3074.92" data-density="527.36"><a href="javascript:sym('733')"><span itemprop="name">Toba Tek Singh</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,084,442</td><td class="rpop prio2">1,134,572</td><td class="rpop prio1">1,621,593</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=733">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('734')"><td class="rname" id="i734" data-wiki="Vehari District" data-wd="Q2418982" data-area="4486.78" data-density="465.91"><a href="javascript:sym('734')"><span itemprop="name">Vehari</span></a></td><td class="rstatus">District</td><td class="rpop prio3">1,027,319</td><td class="rpop prio2">1,328,808</td><td class="rpop prio1">2,090,416</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=734">&#8594;</a></td></tr>
</tbody>
<tbody class="admin1">
<tr class="rname" itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('8')"><td class="rname" id="i8" data-wiki="Sindh" data-wd="Q37211" data-area="141397.02" data-density="215.28"><a href="javascript:sym('8')"><span itemprop="name">Sindh</span></a></td><td class="rstatus">Province</td><td class="rpop prio3">14,155,909</td><td class="rpop prio2">19,028,666</td><td class="rpop prio1">30,439,893</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm1id=8">&#8594;</a></td></tr>
</tbody>
<tbody class="admin2">
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('801')"><td class="rname" id="i801" data-wiki="Badin District" data-wd="Q2347462" data-area="6740.6" data-density="177"><a href="javascript:sym('801')"><span itemprop="name">Badin</span></a></td><td class="rstatus">District</td><td class="rpop prio3">640,718</td><td class="rpop prio2">813,335</td><td class="rpop prio1">1,193,081</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=801">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('802')"><td class="rname" id="i802" data-wiki="Dadu District" data-wd="Q1082679" data-area="7712.49" data-density="143.5"><a href="javascript:sym('802')"><span itemprop="name">Dadu</span></a></td><td class="rstatus">District</td><td class="rpop prio3">556,669</td><td class="rpop prio2">705,669</td><td class="rpop prio1">1,106,717</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=802">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('803')"><td class="rname" id="i803" data-wiki="Ghotki District" data-wd="Q2418935" data-area="6427.98" data-density="150.67"><a href="javascript:sym('803')"><span itemprop="name">Ghotki</span></a></td><td class="rstatus">District</td><td class="rpop prio3">401,318</td><td class="rpop prio2">558,058</td><td class="rpop prio1">968,490</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=803">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('804')"><td class="rname" id="i804" data-wiki="Hyderabad District, Sindh" data-wd="Q2419054" data-area="1021.62" data-density="1463.24"><a href="javascript:sym('804')"><span itemprop="name">Hyderabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">814,060</td><td class="rpop prio2">1,005,460</td><td class="rpop prio1">1,494,866</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=804">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('805')"><td class="rname" id="i805" data-wiki="Jacobabad District" data-wd="Q32852" data-area="2687.78" data-density="276.03"><a href="javascript:sym('805')"><span itemprop="name">Jacobabad</span></a></td><td class="rstatus">District</td><td class="rpop prio3">402,114</td><td class="rpop prio2">586,234</td><td class="rpop prio1">741,910</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=805">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('821')"><td class="rname" id="i821" data-wiki="Jamshoro District" data-wd="Q74192" data-area="11183.27" data-density="52.05"><a href="javascript:sym('821')"><span itemprop="name">Jamshoro</span></a></td><td class="rstatus">District</td><td class="rpop prio3">254,318</td><td class="rpop prio2">375,942</td><td class="rpop prio1">582,094</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=821">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('806')"><td class="rname" id="i806" data-wiki="Karachi" data-wd="Q8660" data-area="3541.42" data-density="2783.15"><a href="javascript:sym('806')"><span itemprop="name">Karachi</span></a> (<span itemprop="name">incl. Karachi Central, Karachi East, Karachi South, Karachi West, Korangi, Malir</span>)</td><td class="rstatus">Districts</td><td class="rpop prio3">3,606,746</td><td class="rpop prio2">5,437,984</td><td class="rpop prio1">9,856,318</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=806">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('822')"><td class="rname" id="i822" data-wiki="Kashmore District" data-wd="Q32850" data-area="2776.38" data-density="238.58"><a href="javascript:sym('822')"><span itemprop="name">Kashmore</span></a></td><td class="rstatus">District</td><td class="rpop prio3">299,589</td><td class="rpop prio2">413,629</td><td class="rpop prio1">662,400</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=822">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('810')"><td class="rname" id="i810" data-wiki="Khairpur District" data-wd="Q2512083" data-area="15920.5" data-density="97.14"><a href="javascript:sym('810')"><span itemprop="name">Khairpur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">724,935</td><td class="rpop prio2">981,190</td><td class="rpop prio1">1,546,587</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=810">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('811')"><td class="rname" id="i811" data-wiki="Larkana District" data-wd="Q2281289" data-area="1905.91" data-density="526.14"><a href="javascript:sym('811')"><span itemprop="name">Larkana</span></a></td><td class="rstatus">District</td><td class="rpop prio3">460,735</td><td class="rpop prio2">572,006</td><td class="rpop prio1">1,002,772</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=811">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('823')"><td class="rname" id="i823" data-wiki="Matiari District" data-wd="Q112797" data-area="1455.94" data-density="339.47"><a href="javascript:sym('823')"><span itemprop="name">Matiari</span></a></td><td class="rstatus">District</td><td class="rpop prio3">336,367</td><td class="rpop prio2">438,319</td><td class="rpop prio1">494,244</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=823">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('813')"><td class="rname" id="i813" data-wiki="Mirpur Khas District" data-wd="Q82253" data-area="2977.74" data-density="304.24"><a href="javascript:sym('813')"><span itemprop="name">Mirpur Khas</span></a></td><td class="rstatus">District</td><td class="rpop prio3">390,884</td><td class="rpop prio2">577,879</td><td class="rpop prio1">905,935</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=813">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('814')"><td class="rname" id="i814" data-wiki="Naushahro Feroze District" data-wd="Q63711" data-area="3036.51" data-density="358.17"><a href="javascript:sym('814')"><span itemprop="name">Naushahro Feroze</span></a></td><td class="rstatus">District</td><td class="rpop prio3">685,829</td><td class="rpop prio2">829,051</td><td class="rpop prio1">1,087,571</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=814">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('824')"><td class="rname" id="i824" data-wiki="Qambar Shahdadkot District" data-wd="Q63710" data-area="5505.64" data-density="167.88"><a href="javascript:sym('824')"><span itemprop="name">Qambar Shahdadkot</span></a></td><td class="rstatus">District</td><td class="rpop prio3">460,722</td><td class="rpop prio2">566,574</td><td class="rpop prio1">924,294</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=824">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('816')"><td class="rname" id="i816" data-wiki="Sanghar District" data-wd="Q1777286" data-area="10765.93" data-density="132.08"><a href="javascript:sym('816')"><span itemprop="name">Sanghar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">674,210</td><td class="rpop prio2">893,047</td><td class="rpop prio1">1,421,977</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=816">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('815')"><td class="rname" id="i815" data-wiki="Shaheed Benazirabad District" data-wd="Q64170" data-area="4496.88" data-density="245.19"><a href="javascript:sym('815')"><span itemprop="name">Shaheed Benazir Abad</span></a> (<span itemprop="name">Nawabshah</span>)</td><td class="rstatus">District</td><td class="rpop prio3">678,982</td><td class="rpop prio2">838,350</td><td class="rpop prio1">1,102,584</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=815">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('817')"><td class="rname" id="i817" data-wiki="Shikarpur District" data-wd="Q2315433" data-area="2560.19" data-density="343.9"><a href="javascript:sym('817')"><span itemprop="name">Shikarpur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">530,551</td><td class="rpop prio2">596,409</td><td class="rpop prio1">880,438</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=817">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('825')"><td class="rname" id="i825" data-wiki="Sujawal District" data-wd="Q16900852" data-area="8734.55" data-density="60.61"><a href="javascript:sym('825')"><span itemprop="name">Sujawal</span></a></td><td class="rstatus">District</td><td class="rpop prio3">356,338</td><td class="rpop prio2">361,799</td><td class="rpop prio1">529,412</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=825">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('818')"><td class="rname" id="i818" data-wiki="Sukkur District" data-wd="Q32854" data-area="5199.3" data-density="179.2"><a href="javascript:sym('818')"><span itemprop="name">Sukkur</span></a></td><td class="rstatus">District</td><td class="rpop prio3">460,649</td><td class="rpop prio2">575,962</td><td class="rpop prio1">931,694</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=818">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('826')"><td class="rname" id="i826" data-wiki="Tando Allahyar District" data-wd="Q112790" data-area="1547.45" data-density="318.93"><a href="javascript:sym('826')"><span itemprop="name">Tando Allahyar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">256,994</td><td class="rpop prio2">329,370</td><td class="rpop prio1">493,526</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=826">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('827')"><td class="rname" id="i827" data-wiki="Tando Muhammad Khan District" data-wd="Q112805" data-area="1550.57" data-density="226.89"><a href="javascript:sym('827')"><span itemprop="name">Tando Muhammad Khan</span></a></td><td class="rstatus">District</td><td class="rpop prio3">218,443</td><td class="rpop prio2">249,156</td><td class="rpop prio1">351,815</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=827">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('819')"><td class="rname" id="i819" data-wiki="Tharparkar District" data-wd="Q2315507" data-area="19890.99" data-density="45.97"><a href="javascript:sym('819')"><span itemprop="name">Tharparkar</span></a></td><td class="rstatus">District</td><td class="rpop prio3">359,357</td><td class="rpop prio2">540,985</td><td class="rpop prio1">914,291</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=819">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('820')"><td class="rname" id="i820" data-wiki="Thatta District" data-wd="Q2419234" data-area="8253.9" data-density="70.73"><a href="javascript:sym('820')"><span itemprop="name">Thatta</span></a></td><td class="rstatus">District</td><td class="rpop prio3">319,698</td><td class="rpop prio2">399,240</td><td class="rpop prio1">583,782</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=820">&#8594;</a></td></tr>
<tr itemscope="" itemtype="http://schema.org/AdministrativeArea" onclick="javascript:sym('828')"><td class="rname" id="i828" data-wiki="Umerkot District" data-wd="Q2418946" data-area="5503.5" data-density="120.49"><a href="javascript:sym('828')"><span itemprop="name">Umerkot</span></a></td><td class="rstatus">District</td><td class="rpop prio3">265,683</td><td class="rpop prio2">383,018</td><td class="rpop prio1">663,095</td><td class="sc"><a itemprop="url" href="pakistan-admin.php?adm2id=828">&#8594;</a></td></tr>
</tbody>
<tbody class="admin0">
<tr><td class="rname">Pakistan</td><td class="rstatus">Republic</td><td class="rpop prio3">65,309,340</td><td class="rpop prio2">84,253,644</td><td class="rpop prio1">132,352,279</td><td class="sc"></td></tr>
</tbody>
</table>
<section id="sourcesection">
<p class="source"><strong>Source:</strong> Pakistan Bureau of Statistics (web), U.S. Bureau of Census: Demobase Pakistan (web).<br>Administrive units as defined in 2014. Districts established between 2010 and 2014 are computed (if possible) by using tehsil data. Therefore, discrepancies to the actual situation may occur.<br>The Pakistani-administered parts of Kashmir are not included.</p>
</section>
<script>var addMapData = []; var addMapMetadata = []</script>
<div class="mobiadv">
	<script>show_mobiadv()</script>
</div>
<div id="advhor">
	<script>show_adv('h');</script>
</div>
<script>writeFooter('2016-01-01')</script>
</article>

<div id="admmap" itemprop="geo" itemscope="" itemtype="http://schema.org/GeoCoordinates">
	<meta itemprop="latitude" content="31">
	<meta itemprop="longitude" content="69">
	<div id="mapcontainer">
	<div id="mapdiv">
		<div id="maplconrl"></div>
	 <div id="maprconrl"></div>
	</div>
	</div>
</div>
<div id="alert"></div>
<div id="helpdiv"></div>
<div id="adv">
	<script>show_adv();</script>
</div>
<script>
	var startChartID = "PAK"; var startChartType = "adm0";
	var minlat = 23.694; var minlng = 60.873; var maxlat = 36.912; var maxlng = 75.38;
	if (cp.getVizMode() == cp.VIZMODE_DESKTOP) cp.social.addSocial(false);
</script>
</body>
</html>
<!-- create time: 0.13836002349854 -->
<!-- cache time: 0.0012209415435791 -->